### PR TITLE
Tell how to get the submodules

### PR DESCRIPTION
**Pull request by clemens-tolboom**

### CODE REVIEW

**Comment by fire** [comment]
Using https://github.com/godot-extended-libraries/godot-tensorflow-workspace.git is slightly more compatible.

**Comment by clemens-tolboom** [comment]
Thanks for the quick response.

> Go to src/thirdparty/godot

I cannot `cd` into so the instruction is not working for me.

My steps:

- clone this repo https://github.com/godot-extended-libraries/godot-tensorflow-workspace
- follow the steps
- fail.

Navigating to https://github.com/godot-extended-libraries/godot-tensorflow-workspace/tree/master/src there is a submodule which I do not get when cloning.

What do I miss apart from this PR steps?

**Comment by fire** [comment]
Let me use git bash and try following my own instructions. Will report back.

**Comment by fire** [comment]
```$ git clone  https://github.com/godot-extended-libraries/godot-tensorflow-workspace --recursive```

is a lot simpler.

Had to:

```
$ cd godot-tensorflow-workspace/
$ cd src/godot/
```

Have to open the project in the Godot Engine editor once.

```
$ ./bin/godot.windows.tools.64.exe --path ../../godot-tensorflow-demo/ -v -e
```

**Comment by clemens-tolboom** [comment]
Fair enough it looks cleaner

```
git clone  \
  --recursive \
  https://github.com/godot-extended-libraries/godot-tensorflow-workspace
```

but does not trigger the mind to use submodule command when pulling in latest. Or does it?

I did `git submodule update --recursive` to get your latest ... not sure `git pull` can do this too.

**Comment by clemens-tolboom** [comment]
We can close this as @fire fixed it another way.

**Pull request closed without merging**
